In [2]:
import pandas as pd

In [3]:
labelled_df=pd.read_csv("..//BETH/labelled_training_data.csv")

In [4]:
labelled_df.head()

,timestamp,processId,threadId,parentProcessId,userId,mountNamespace,processName,hostName,eventId,eventName,stackAddresses,argsNum,returnValue,args,sus,evil
0,1809.495787,381,7337,1,100,4026532231,close,ip-10-100-1-120,157,prctl,"[140662171848350, 11649800180280676]",5,0,"[{'name': 'option', 'type': 'int', 'value': 'P...",1,0
1,1809.495832,381,7337,1,100,4026532231,close,ip-10-100-1-120,3,close,[140662171777451],1,0,"[{'name': 'fd', 'type': 'int', 'value': 19}]",1,0
2,1809.495921,381,7337,1,100,4026532231,close,ip-10-100-1-120,1010,sched_process_exit,[],0,0,[],1,0
3,1894.139651,7347,7347,7341,0,4026531840,sh,ip-10-100-1-120,21,access,[],2,-2,"[{'name': 'pathname', 'type': 'const char*', '...",1,0
4,1894.142127,7347,7347,7341,0,4026531840,sh,ip-10-100-1-120,1005,security_file_open,"[139778263990104, 139778263906698]",4,0,"[{'name': 'pathname', 'type': 'const char*', '...",1,0

In [5]:
labelled_df.tail()

,timestamp,processId,threadId,parentProcessId,userId,mountNamespace,processName,hostName,eventId,eventName,stackAddresses,argsNum,returnValue,args,sus,evil
763139,324.542553,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,1003,cap_capable,[],1,0,"[{'name': 'cap', 'type': 'int', 'value': 'CAP_...",0,0
763140,324.542579,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,62,kill,[],2,0,"[{'name': 'pid', 'type': 'pid_t', 'value': 0},...",0,0
763141,324.543178,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,1010,sched_process_exit,[],0,0,[],0,0
763142,324.543695,7275,7275,1,109,4026531840,sshd,ip-10-100-1-79,1010,sched_process_exit,[],0,0,[],0,0
763143,324.543831,7108,7108,1,0,4026531840,sshd,ip-10-100-1-79,3,close,[140129105123719],1,0,"[{'name': 'fd', 'type': 'int', 'value': 6}]",0,0

In [6]:
labelled_df.shape

(763144, 16)

In [7]:
labelled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 763144 entries, 0 to 763143
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   timestamp        763144 non-null  float64
 1   processId        763144 non-null  int64
 2   threadId         763144 non-null  int64
 3   parentProcessId  763144 non-null  int64
 4   userId           763144 non-null  int64
 5   mountNamespace   763144 non-null  int64
 6   processName      763144 non-null  object
 7   hostName         763144 non-null  object
 8   eventId          763144 non-null  int64
 9   eventName        763144 non-null  object
 10  stackAddresses   763144 non-null  object
 11  argsNum          763144 non-null  int64
 12  returnValue      763144 non-null  int64
 13  args             763144 non-null  object
 14  sus              763144 non-null  int64
 15  evil             763144 non-null  int64
dtypes: float64(1), int64(10), object(5)
memory usage: 93.2+ MB

In [8]:
labelled_df[labelled_df.duplicated()]

Empty DataFrame
Columns: [timestamp, processId, threadId, parentProcessId, userId, mountNamespace, processName, hostName, eventId, eventName, stackAddresses, argsNum, returnValue, args, sus, evil]
Index: []

Observations about the dataset: -
1. The dataset has 7,63,144 rows and 16 columns.
2. There are no duplicate rows.
3. There are no null values.
4. There are two target features: sus, evil
   * sus: Binary label indicating suspicious event as 1 otherwise 0.
   * evil: Binary label indicating known malicious event as 1 otherwise 0.