In [1]:
import pandas as pd

In [2]:
data_df=pd.read_csv("..//UNR-IDD/UNR-IDD.csv")

In [3]:
data_df.head()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,...,Unknown Load/Latest,Latest bytes counter,is_valid,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,Label,Binary Label
0,of:000000000000000c,Port#:1,132,9181,6311853,238,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
1,of:000000000000000c,Port#:2,187,6304498,15713,171,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
2,of:000000000000000c,Port#:3,235,6311567,8030,58,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
3,of:000000000000000c,Port#:4,59,7878,16439,182,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
4,of:000000000000000a,Port#:1,188,6304547,16497,183,46,0,0,0,...,0,0,True,0,7,489,403,-1,TCP-SYN,Attack

In [4]:
data_df.tail()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,...,Unknown Load/Latest,Latest bytes counter,is_valid,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,Label,Binary Label
37406,of:0000000000000006,Port#:2,228,30195,7857046,145141,276,0,0,0,...,0,0,True,0,6,147563,147454,-1,PortScan,Attack
37407,of:0000000000000006,Port#:3,1064,18962056,37732,338,276,0,0,0,...,0,0,True,0,6,147563,147454,-1,PortScan,Attack
37408,of:0000000000000009,Port#:1,1042,25252012,7856976,145140,276,0,0,0,...,0,0,True,0,8,295511,295404,-1,PortScan,Attack
37409,of:0000000000000009,Port#:2,149012,14360115,29509,211,276,0,0,0,...,0,0,True,0,8,295511,295404,-1,PortScan,Attack
37410,of:0000000000000009,Port#:3,228,30377,25258600,1138,276,0,0,0,...,0,0,True,0,8,295511,295404,-1,PortScan,Attack

In [5]:
data_df.shape

(37411, 34)

In [6]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37411 entries, 0 to 37410
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Switch ID                      37411 non-null  object
 1   Port Number                    37411 non-null  object
 2   Received Packets               37411 non-null  int64
 3   Received Bytes                 37411 non-null  int64
 4   Sent Bytes                     37411 non-null  int64
 5   Sent Packets                   37411 non-null  int64
 6   Port alive Duration (S)        37411 non-null  int64
 7   Packets Rx Dropped             37411 non-null  int64
 8   Packets Tx Dropped             37411 non-null  int64
 9   Packets Rx Errors              37411 non-null  int64
 10  Packets Tx Errors              37411 non-null  int64
 11  Delta Received Packets         37411 non-null  int64
 12  Delta Received Bytes           37411 non-null  int64
 13  Delta Sent Bytes               37411 non-null  int64
 14  Delta Sent Packets             37411 non-null  int64
 15  Delta Port alive Duration (S)  37411 non-null  int64
 16  Delta Packets Rx Dropped       37411 non-null  int64
 17   Delta Packets Tx Dropped      37411 non-null  int64
 18  Delta Packets Rx Errors        37411 non-null  int64
 19  Delta Packets Tx Errors        37411 non-null  int64
 20  Connection Point               37411 non-null  int64
 21  Total Load/Rate                37411 non-null  int64
 22  Total Load/Latest              37411 non-null  int64
 23  Unknown Load/Rate              37411 non-null  int64
 24  Unknown Load/Latest            37411 non-null  int64
 25  Latest bytes counter           37411 non-null  int64
 26  is_valid                       37411 non-null  bool
 27  Table ID                       37411 non-null  int64
 28  Active Flow Entries            37411 non-null  int64
 29  Packets Looked Up              37411 non-null  int64
 30  Packets Matched                37411 non-null  int64
 31  Max Size                       37411 non-null  int64
 32  Label                          37411 non-null  object
 33  Binary Label                   37411 non-null  object
dtypes: bool(1), int64(29), object(4)
memory usage: 9.5+ MB

In [7]:
data_df['Label'].unique()

array(['TCP-SYN', 'Blackhole', 'Diversion', 'Overflow', 'Normal',
       'PortScan'], dtype=object)

In [8]:
data_df["Binary Label"].unique()

array(['Attack', 'Normal'], dtype=object)

In [9]:
data_df.isna().sum()

Switch ID                        0
Port Number                      0
Received Packets                 0
Received Bytes                   0
Sent Bytes                       0
Sent Packets                     0
Port alive Duration (S)          0
Packets Rx Dropped               0
Packets Tx Dropped               0
Packets Rx Errors                0
Packets Tx Errors                0
Delta Received Packets           0
Delta Received Bytes             0
Delta Sent Bytes                 0
Delta Sent Packets               0
Delta Port alive Duration (S)    0
Delta Packets Rx Dropped         0
 Delta Packets Tx Dropped        0
Delta Packets Rx Errors          0
Delta Packets Tx Errors          0
Connection Point                 0
Total Load/Rate                  0
Total Load/Latest                0
Unknown Load/Rate                0
Unknown Load/Latest              0
Latest bytes counter             0
is_valid                         0
Table ID                         0
Active Flow Entries              0
Packets Looked Up                0
Packets Matched                  0
Max Size                         0
Label                            0
Binary Label                     0
dtype: int64

In [10]:
data_df[data_df.duplicated()]

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,...,Unknown Load/Latest,Latest bytes counter,is_valid,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,Label,Binary Label
32287,of:000000000000000a,Port#:3,66,9078,8992,63,56,0,0,0,...,0,0,True,0,4,201,123,-1,PortScan,Attack

Observations from dataset: -

1. The dataset has 37,411 rows and 34 columns.
2. There are no null values in the dataset.
3. The numerical fields are raw and not normalized.
4. There is only one duplicate record.
5. There are two target features: Label and Binary Label for Multi-class classification and Binary classification respectively.